# Session 01 Homework


As the environment has already been set up, we can process to answer questions.



## Q1. Pandas version


In [1]:
import pandas as pd
pd.__version__

'2.2.3'

# Get the data

For this homework, we'll use the Car Fuel Efficiency dataset. Download it from here.

You can do it with wget:

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q2. Records count


In [7]:
len(df)

9704

### Q3. Fuel types


In [10]:
df.fuel_type.nunique()

2

### Q4. Missing values


In [ ]:
# Number of columns with missing values
num_cols_with_missing = df.isnull().any().sum()
print(num_cols_with_missing)

4


### Q5. Max fuel efficiency


In [ ]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

23.759122836520497

### Q6. Median value of horsepower
1. Find the median value of `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?

In [ ]:
# Original median
median_before = df['horsepower'].median()

# Most frequent
mode_hp = df['horsepower'].mode()[0]

# Fill NaNs
df_hp = df.copy()
df_hp['horsepower'] = df_hp['horsepower'].fillna(mode_hp)

# New median
median_after = df_hp['horsepower'].median()

median_before, mode_hp, median_after


(152.0, np.float64(152.0), 152.0)

### Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

**Note**: You just implemented linear regression. We'll talk about it in the next lesson.

In [ ]:
# Select Asia cars, only columns vehicle_weight & model_year
asia_cars = df[df["origin"] == "Asia"]

# Visualize
asia_cars.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [42]:
# Subset of data
asia_cars_subset = asia_cars[["vehicle_weight", "model_year"]]

# Select the first 7 values to make the computation easier to check
asia_cars_subset = asia_cars_subset.iloc[:7]
# result
asia_cars_subset

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [43]:
# import numpy package
import numpy as np

# Create array of data
X = np.array(asia_cars_subset)
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [44]:
# Step 2: Compute matrix multiplication and invert
XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [45]:
# Step 3: Create y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [46]:
# Step 4: Compute w
w = XTX_inv.dot(X.T).dot(y)

# Step 5: Sum of w
w.sum()

np.float64(0.5187709081074007)

In [47]:
# Step 5: Sum of w
w.sum()

np.float64(0.5187709081074007)